### ISSUE TITLE
Provider GET /stats endpoint returns null arrays instead of empty JSON arrays.

### ISSUE THREAD

**Issue by AlexSteele** [uofu-skybin/skybin#28]
This causes errors in the front end when trying to render stats charts.

It seems only to occur when the provider is first initialized before it has received any requests.

**Comment by AlexSteele** [comment]
Are you sure? I do not see why that would fix the problem. We should not call fetchStats() prior to ensuring that the provider has been set up.

**Comment by AlexSteele** [comment]
Right. It shouldn't be called until a provider is registered. The issue this GitHub issue refers to occurs after fetchStats() is called but before the provider has received any network traffic. In that case, null arrays are sent back from the provider node in several stats fields and these calls null pointer exceptions in the javascript chart code.

**Comment by zakpeters** [comment]
Hmmm. Actually just switched back to master and it seems to be working fine for me. I was having a weird bug where the provide storage dashboard would remain entirely blank earlier and thought that was what you were talking about.

Have you changed updated the skybin executable in the portal recently?

**Comment by AlexSteele** [comment]
You are right. This is not a problem on master. My mistake.
