### ISSUE TITLE
Document provider GET /info endpoint and improve response field names.

### ISSUE THREAD

**Issue by AlexSteele** [uofu-skybin/skybin#6]
Please add this endpoint to the API doc. Also, I think we could probably improve the response field naming to be more descriptive and avoid prefixing each field with "provider". 

See [here ](https://github.com/uofu-skybin/skybin/blob/974393271b829ec302226d2fe80fa660db0414a5/provider/server.go#L249) for the relevant code.

**Comment by zakpeters** [comment]
Yeah, it was hacky. I will refactor this whole component when finals are past.
